import math

d1 = input("Введите кратчайшее расстояние между спасателем и кромкой воды, d1 (ярды) => ")
print(d1)
d1 = float(d1)
d2 = input("Введите кратчайшее расстояние от утопающего до берега, d2 (футы) => ")
print(d2)
d2 = float(d2)
h = input("Введите боковое смещение между спасателем и утопающим, h (ярды) => ")
print(h)
h = float(h)
v_sand = input("Введите скорость движения спасателя по песку, v_sand (мили в час) => ")
print(v_sand)
v_sand = float(v_sand)
n = input("Введите коэффициент замедления спасателя при движении в воде, n => ")
print(n)
n = float(n)
theta1 = input("Введите направление движения спасателя по песку, theta1 (градусы) => ")
print(theta1)
theta1 = float(theta1)
x = d1 * math.tan(theta1 * math.pi/180)
#print(x)
L1 = math.sqrt(x**2+d1**2)
#print(L1)
L2 = math.sqrt((h-x)**2 + (d2/3)**2)
#print(L2)
t = (1/(v_sand*5280/3))*(L1+n*L2)*3600
#print(t)
print(f"Если спасатель начнёт движение под углом theta1, равным {theta1:.0f} градусам, он достигнет утопающего через {t:.1f} секунды")